

POST https://api.trakt.tv/oauth/token HTTP/1.1
content-type: application/json

{
"code": "cc33fc740bbf33e20546f7e0e1b788c15302a3d511881e318dbac0d69eee4a19",
"client_id": "18bde7dcd858c86f9593addf9f66528f8c1443ec1bef9ecee501d1c5177ce281",
"client_secret": "d4214fec4f6f994b79f03430f19441120a44c67441c06cc1dd10dc92d7967b0c",
"redirect_uri": "https://2ecbbd610840-trakt.baby-beamup.club",
"grant_type": "authorization_code"
}

trakt_list:5308818:title,asc
###
http://127.0.0.1:63355/bGlzdHM9dHJha3RfdHJlbmRpbmcsdHJha3RfcG9wdWxhcnxpZHM9Z2FyeWNyYXdmb3JkZ2M6dG9wLW1vdmllcy1vZi10aGUtd2VlazpyYW5rOmFzYyxnYXJ5Y3Jhd2ZvcmRnYzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjLGdpbGFkZzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjfGFjY2Vzc190b2tlbj04NjA5ZjRiMjE4YTMyYjExODhmNDkyNTkwNTEwZWI2ZWIyMTUxNDNkY2RiZGQ5YjBjN2YzOGVlYjdlZWE1Njhl/catalog/trakt/trakt_list:5308818:title,asc.json

###
http://127.0.0.1:63355/bGlzdHM9dHJha3RfdHJlbmRpbmcsdHJha3RfcG9wdWxhcnxpZHM9Z2FyeWNyYXdmb3JkZ2M6dG9wLW1vdmllcy1vZi10aGUtd2VlazpyYW5rOmFzYyxnYXJ5Y3Jhd2ZvcmRnYzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjLGdpbGFkZzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjfGFjY2Vzc190b2tlbj04NjA5ZjRiMjE4YTMyYjExODhmNDkyNTkwNTEwZWI2ZWIyMTUxNDNkY2RiZGQ5YjBjN2YzOGVlYjdlZWE1Njhl/catalog/trakt/trakt_list:5308818:title,asc/skip=100.json

###
http://127.0.0.1:63355/bGlzdHM9dHJha3RfdHJlbmRpbmcsdHJha3RfcG9wdWxhcnxpZHM9Z2FyeWNyYXdmb3JkZ2M6dG9wLW1vdmllcy1vZi10aGUtd2VlazpyYW5rOmFzYyxnYXJ5Y3Jhd2ZvcmRnYzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjLGdpbGFkZzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjfGFjY2Vzc190b2tlbj04NjA5ZjRiMjE4YTMyYjExODhmNDkyNTkwNTEwZWI2ZWIyMTUxNDNkY2RiZGQ5YjBjN2YzOGVlYjdlZWE1Njhl/catalog/trakt/trakt_list:5308818:title,asc/skip=200.json

###
http://127.0.0.1:63355/bGlzdHM9dHJha3RfdHJlbmRpbmcsdHJha3RfcG9wdWxhcnxpZHM9Z2FyeWNyYXdmb3JkZ2M6dG9wLW1vdmllcy1vZi10aGUtd2VlazpyYW5rOmFzYyxnYXJ5Y3Jhd2ZvcmRnYzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjLGdpbGFkZzpsYXRlc3QtcmVsZWFzZXM6YWRkZWQ6YXNjfGFjY2Vzc190b2tlbj04NjA5ZjRiMjE4YTMyYjExODhmNDkyNTkwNTEwZWI2ZWIyMTUxNDNkY2RiZGQ5YjBjN2YzOGVlYjdlZWE1Njhl/catalog/trakt/trakt_list:5308818:title,asc/skip=300.json